apiVersion: v2
name: fortify
description: A Helm chart for Kubernetes
type: application
version: 0.0.2
appVersion: "21.1.2.0005"
dependencies:
- name: mysql
  condition: mysql.enabled
  version: '*.*.*'
  repository: file://./charts/mysql-8.4.3.tgz