apiVersion: v2
name: fortify
description: A Helm chart for Microfocus Fortify SSC
type: application
version: 0.0.7-bb.0
appVersion: "22.1.1.0006"
dependencies:
- name: mysql
  condition: mysql.enabled
  version: '9.2.1'
  repository: https://charts.bitnami.com/bitnami
