apiVersion: v2
description: A Helm chart for Fortify Software Security Center application
name: fortify-ssc
version: 1.1.2320154-bb.36
appVersion: 25.2.1.0010
type: application
keywords:
- fortify
- ssc
- sast
home: https://www.microfocus.com/en-us/solutions/application-security
icon: https://avatars.githubusercontent.com/u/28990234?s=200&v=ok
sources:
- https://github.com/fortify/helm3-charts
engine: gotpl
dependencies:
- name: mysql
  # TODO: this should be changed to registry1.dso.mil/ironbank/mysql when/if it is available (at modern versions)
  condition: mysql.enabled
  version: '9.19.0'
  repository: oci://registry-1.docker.io/bitnamicharts
- name: gluon
  version: 0.5.20
  repository: oci://registry1.dso.mil/bigbang
annotations:
  bigbang.dev/maintenanceTrack: bb_integrated
  bigbang.dev/upstreamReleaseNotesMarkdown: |
    - [Find our upstream chart's CHANGELOG here](https://github.com/fortify/helm3-charts/tree/main/charts)
    - [and our upstream application release notes here](https://www.microfocus.com/documentation/fortify-core-documents/2420/FortifySW_RN_24.2.0.pdf)
  bigbang.dev/applicationVersions: |
    - Fortify: 25.2.1.0010
  helm.sh/images: |
    - name: ssc
      image: registry1.dso.mil/ironbank/microfocus/fortify/ssc:25.2.1.0010
    - name: mysql
      image: registry1.dso.mil/ironbank/bitnami/mysql8:8.0.36-debian-11-r1
    - name: golang-1.24
      image: registry1.dso.mil/ironbank/google/golang/ubi9/golang-1.24:1.24.8
