apiVersion: v2
name: fortify
description: A Helm chart for Microfocus Fortify SSC
type: application
version: 0.0.9-bb.2
appVersion: 22.1.2.0004
dependencies:
- name: mysql
  condition: mysql.enabled
  version: '9.3.4'
  repository: https://charts.bitnami.com/bitnami
annotations:
  bigbang.dev/applicationVersions: |
    - Fortify: 22.1.2.0004
  helm.sh/images: |
    - name: velero-plugin-for-csi
      image: registry1.dso.mil/ironbank/microfocus/fortify/ssc:22.1.2.0004
    - name: mysql8
      condition: mysql.enabled
      image: registry1.dso.mil/ironbank/bitnami/mysql8:8.0.29-debian-10-r37
