apiVersion: v2
name: fortify
description: A Helm chart for Microfocus Fortify SSC
type: application
version: 0.2.0-bb.0
appVersion: 23.1.1.0007
dependencies:
- name: mysql
  condition: mysql.enabled
  version: '9.10.9'
  repository: https://charts.bitnami.com/bitnami
annotations:
  bigbang.dev/applicationVersions: |
    - Fortify: 23.1.1.0007
  helm.sh/images: |
    - name: ssc
      image: registry1.dso.mil/ironbank/microfocus/fortify/ssc:23.1.1.0007
    - name: keystore
      image: registry1.dso.mil/ironbank/redhat/openjdk/openjdk13:1.13.0
    - name: mysql8
      condition: mysql.enabled
      image: registry1.dso.mil/ironbank/bitnami/mysql8:8.0.29-debian-10-r37
