apiVersion: v2
name: fortify
description: A Helm chart for Microfocus Fortify SSC
type: application
version: 0.0.5
appVersion: "21.2.2.0002"
dependencies:
- name: mysql
  condition: mysql.enabled
  version: '*.*.*'
  repository: file://./charts/mysql-8.4.3.tgz