apiVersion: v2
description: A Helm chart for Fortify Software Security Center application
name: fortify-ssc
version: 1.1.2320154-bb.3
appVersion: 23.2.0.0154
type: application
keywords:
- fortify
- ssc
- sast
home: https://www.microfocus.com/en-us/solutions/application-security
icon: https://avatars.githubusercontent.com/u/28990234?s=200&v=4
sources:
- https://github.com/fortify/helm3-charts
engine: gotpl
dependencies:
- name: mysql
  # TODO: this should be changed to registry1.dso.mil/ironbank/mysql when/if it is available (at modern versions)
  condition: mysql.enabled
  version: '9.14.4'
  repository: oci://registry-1.docker.io/bitnamicharts
- name: gluon
  version: 0.4.7
  repository: oci://registry1.dso.mil/bigbang
annotations:
  bigbang.dev/applicationVersions: |
    - Fortify: 23.2.0.0154
  helm.sh/images: |
    - name: ssc
      image: registry1.dso.mil/ironbank/microfocus/fortify/ssc:23.2.0.0154
    - name: mysql
      image: registry1.dso.mil/ironbank/bitnami/mysql8:8.0.35-debian-11-r1
    - name: golang-1.20
      image: registry1.dso.mil/ironbank/google/golang/golang-1.20:1.20.12
