apiVersion: v2
name: fortify
description: A Helm chart for Microfocus Fortify SSC
type: application
version: 0.0.6-bb.0
appVersion: "22.1.0.0149"
dependencies:
- name: mysql
  condition: mysql.enabled
  version: '*.*.*'
  repository: file://./charts/mysql-8.8.12.tgz
