apiVersion: v2
name: fortify
description: A Helm chart for Microfocus Fortify SSC
type: application
version: 0.0.7-bb.0
appVersion: "22.1.1.0006"
dependencies:
- name: mysql
  condition: mysql.enabled
  version: '9.2.1'
  repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
