# fortify Image
image:
  repository: registry.dso.mil/platform-one/big-bang/apps/developer-tools/fortify/scc-webapp
  pullPolicy: IfNotPresent
  tag: 20.1.0.0169
  imagePullSecrets: ""

# fortify configuration
# Defaults configured no need to change unless necessary. 
license_path: /app/secrets/fortify-license
auto_config: /app/secrets/fortify-autoconfig
http_server_certificate_keystore_file: /app/secrets/httpCertificateKeystoreFile
http_server_certificate_keystore_password: /app/secrets/httpCertificateKeystorePassword
https_server_certificate_key_password: /app/secrets/httpCertificateKeyPassword
enforce_secure_transport: false
jdbc_driver: https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.21/mysql-connector-java-8.0.21.jar

# configurable parameters
hostname: "fortify.bigbang.dev"
replicaCount: 1
http_server_cert_alias: ""
key_store_password: ""
key_store_cert_password : ""
port:
  http: 8080
  https: 8443
resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1
    memory: 1Gi
initContainer:
  image: registry.dso.mil/platform-one/big-bang/apps/developer-tools/fortify/mysql-client
  tag: 8.0.21
imagePullSecrets: private-registry
# I dont like to add this a configmap which will fail the rule encoded at rest
fortify_autoconfig: |
  appProperties: {
    host.validation: false,
    searchIndex.location: '/app/tomcat/fortify/ssc/ssc_search_index'
  }
  datasourceProperties: {
    jdbc.url: "jdbc:mysql://fortify-mysql:3306/fortify?useSSL=false&connectionCollation=<collation>&rewriteBatchedStatements=true&max_allowed_packet=1073741824&sql_mode=TRADITIONAL",
    db.driver.class: com.mysql.cj.jdbc.Driver,
    db.username: <DB-USER>,
    db.password: <DB-PASSWORD>,
    db.dialect: com.fortify.manager.util.hibernate.MySQLDialect,
    db.like.specialCharacters: '%_\\'
  }
    seeds: [
      '/app/seeds/000-fortify/000-Fortify_Process_Seed_Bundle-2020_Q1_0024.zip',
      '/app/seeds/000-fortify/Fortify_PCI_Basic_Seed_Bundle-2020_Q1_0024.zip',
      '/app/seeds/000-fortify/Fortify_PCI_SSF_Basic_Seed_Bundle-2020_Q1_0024.zip',
      '/app/seeds/000-fortify/Fortify_Report_Seed_Bundle-2020_Q1_0024.zip'
    ]

fortify_license: |
    Full License

# Please read the docs to create java keystore and convert it into base64
fortify_java_keystore: # base64 encoded java keystore binary

# No data will be stored on the EBS you can keep it small
storage:
  volume: 50Gi

# database parameters, this chart wont deploy database
database :
  host: ""
  port: ""
  username: ""
  password: ""