# fortify Image
image:
  repository: registry1.dso.mil/ironbank/microfocus/fortify/ssc
  pullPolicy: IfNotPresent
  tag: 22.1.0.0149
  imagePullSecrets: "private-registry"

enforce_secure_transport: false
jdbc_driver: https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.21/mysql-connector-java-8.0.21.jar
default_cert_alias: dsop

# configurable parameters
hostname: "fortify.bigbang.dev"
replicaCount: 1
runAsRootGroup: true # Likely required for the container to run. OPA exception needed
key_store_password: "" # Required to be at least 8 characters
key_store_cert_password : "" # Required to be at least 8 characters
port:
  http: 8080
  https: 8443
resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1
    memory: 1Gi
initContainer:
  image: registry.dso.mil/platform-one/big-bang/apps/third-party/fortify/mysql-client
  tag: 8.0.21
  keystoreImage: registry1.dso.mil/ironbank/redhat/openjdk/openjdk13
  keystoreTag: 1.13.0
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 250m
      memory: 64Mi

# I dont like to add this a configmap which will fail the rule encoded at rest
fortify_autoconfig: |
  appProperties:
    host.validation: false
    searchIndex.location: '/fortify/ssc/index'
  datasourceProperties:
    jdbc.url: "jdbc:mysql://fortify-mysql:3306/fortify?useSSL=false&connectionCollation=<collation>&rewriteBatchedStatements=true&max_allowed_packet=1073741824&sql_mode=TRADITIONAL"
    db.driver.class: com.mysql.cj.jdbc.Driver
    db.username: <DB-USER>
    db.password: <DB-PASSWORD>
    db.dialect: com.fortify.manager.util.hibernate.MySQLDialect
    db.like.specialCharacters: '%_\\'
  dbMigrationProperties:
    migration.enabled: true

fortify_license: |
    Full License

# Please read the docs to create java keystore and convert it into base64
fortify_java_keystore:
  use: false
  keystore: "ZHVtbXkK" # base64 of keystore

# No data will be stored on the EBS you can keep it small
storage:
  volume: 50Gi

mysql:
  enabled: true
  image:
    registry: "registry1.dso.mil"
    repository: "ironbank/bitnami/mysql8"
    tag: 8.0.29
    pullSecrets:
      - private-registry
  auth:
    rootPassword: "root"
    username: "admin"
    password: "admin"
  fullnameOverride: fortify-mysql

nodeSelector: {}

tolerations: []

affinity: {}

# Big Bang Additions
istio:
  enabled: false
  gateways:
    - istio-system/main

networkPolicies:
  enabled: false
  egress: []
  egressDns: []
  ingress: []

databaseSecret:
  use_secret: false
  name: db-credentials-mysql
  useRoot: false # Use root credentials to create database if required
  # Secret contains following values:
  # DBHOST
  # DBPASSWORD
  # DBUSER
  # DBROOTUSER (optional)
  # DBROOTPASSWORD (optional)

fortifySecret:
  use_secret: false
  name: fortify-secret
  # Secret contains following values:
  # certificate-key-password
  # certificate-keystore-password
  # scc.autoconfig
  # fortify.license
  # Note: certificate-keystore is generated by init container
