{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-istio-web
  namespace: {{ .Release.Namespace | quote }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
    {{- toYaml .Values.networkPolicies.ingress | nindent 4 }}
{{- end }}