---
apiVersion: v1
data:
  DBHOST: {{ .Values.database.host | b64enc | quote }}
  DBPASSWORD: {{ .Values.database.password | b64enc | quote }}
  DBUSER: {{ .Values.database.username | b64enc | quote }}
kind: Secret
metadata:
  name: db-credentials-mysql
  namespace: {{ .Release.Namespace }}

---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: fortify-secret
  namespace: {{ .Release.Namespace }}
data: 
  httpCertificateKeyPassword:  {{ .Values.key_store_cert_password | b64enc | quote }}
  httpCertificateKeystorePassword: {{ .Values.key_store_password | b64enc | quote }}
  httpCertificateKeystoreFile: >-
    {{ .Values.fortify_java_keystore }}
  fortify-autoconfig: {{ .Values.fortify_autoconfig| b64enc | quote }}
  fortify-license: {{ .Values.fortify_license | b64enc | quote }}