{{- $context := merge (dict "component" "secret") . -}}
{{- if not .Values.databaseSecret.use_secret }}
---
apiVersion: v1
data:
  DBHOST: {{ .Values.mysql.fullnameOverride | b64enc | quote }}
  DBPASSWORD: {{ .Values.mysql.auth.password | b64enc | quote }}
  DBUSER: {{ .Values.mysql.auth.username | b64enc | quote }}
  DBROOTUSER: {{ "root" | b64enc | quote }}
  DBROOTPASSWORD: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
kind: Secret
metadata:
  name: db-credentials-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: secret
    app.kubernetes.io/instance: fortify
    app.kubernetes.io/managed-by: flux
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Values.image.tag | quote }}
{{- end }}

{{- if not .Values.fortifySecret.use_secret }}
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: {{ include "ssc.fullcomponentname" $context }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: secret
    app.kubernetes.io/instance: fortify
    app.kubernetes.io/managed-by: flux
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Values.image.tag | quote }}
data: 
  ssc-service.jks.key.password:  {{ .Values.key_store_cert_password | b64enc | quote }}
  ssc-service.jks.password: {{ .Values.key_store_password | b64enc | quote }}
  truststore.password: {{ .Values.trust_store_password | b64enc | quote }}
  {{- if .Values.fortify_java_keystore.use }}
  ssc-service.jks: >-
    {{ .Values.fortify_java_keystore.keystore }}
  {{- end }}
  ssc.autoconfig: {{ .Values.fortify_autoconfig | b64enc | quote }}
  fortify.license: {{ .Values.fortify_license | b64enc | quote }}
{{- end }}