fortify:
  enabled: true
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/third-party/fortify
    path: chart
  flux: {}
  ingress:
    gateway: ""

# Toggle for network polocies
networkPolicies:
  enabled: true

# Toggle for Bigbang Core packages set true to install
jaeger:
  enabled: false

kiali:
  enabled: false

clusterAuditor:
  enabled: false

gatekeeper:
  enabled: false

kyverno:
  enabled: false

tempo:
  enabled: false

promtail:
  enabled: false

loki:
  enabled: false

eckoperator:
  enabled: false

logging:
  enabled: false

fluentbit:
  enabled: false

monitoring:
  enabled: false

twistlock:
  enabled: false

# Toggle for Bigbang Addon packages set true to install
addons:
  argocd:
    enabled: false
  authservice:
    enabled: false
  gitlab:
    enabled: false
  gitlabRunner:
    enabled: false
  anchore:
    enabled: false
  sonarqube:
    enabled: false
  minioOperator:
    enabled: false
  minio:
    enabled: false
  mattermostoperator:
    enabled: false
  mattermost:
    enabled: false
  nexus:
    enabled: false
  velero:
    enabled: false
  keycloak:
    enabled: false
  vault:
    enabled: false
