{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: fortify
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/instance: fortify
    app.kubernetes.io/managed-by: flux
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Values.image.tag | quote }}
spec:
  gateways:
  {{- range .Values.istio.gateways }}
    - {{ . }}
  {{- end }}
  hosts:
    - {{ .Values.hostname }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ .Chart.Name }}-service
        port:
          number: 80
{{- end }}
