{{- $context := merge (dict "component" "service") . -}}
{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: fortify
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/instance: fortify
    app.kubernetes.io/managed-by: flux
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Values.image.tag | quote }}
spec:
  gateways:
  {{- range .Values.istio.fortify.gateways }}
    - {{ . }}
  {{- end }}
  hosts:
  {{- range .Values.istio.fortify.hosts }}
  - {{ tpl . $}}
  {{- end }}
  http:
  - route:
    - destination:
        host: {{ include "ssc.fullcomponentname" $context }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 80
{{- end }}
