{{- $pkg := "fortify" }}
{{- $component := "third-party" }}
{{- define "bigbang.defaults.fortify" -}}
# hostname is deprecated and replaced with domain. But if hostname exists then use it.
domain: {{ default .Values.domain .Values.hostname }}
istio:
  enabled: {{ .Values.istio.enabled }}
  gateways:
    - istio-system/{{ default "public" .Values.fortify.ingress.gateway }}
monitoring:
  enabled: {{ .Values.monitoring.enabled }}
{{- end }}

{{- /* Create secret */ -}}
{{- if (get .Values $pkg).enabled }}
{{- include "values-secret" (dict "root" $ "package" (get .Values $pkg) "name" $pkg "defaults" (include (printf "bigbang.defaults.%s" $pkg) .)) }}
{{- end }}
